export const available_skincare_products = [
  {
    product_name: 'derma decode Silicone Gel Sunscreen SPF 50 PA++++ (50ml)',
    allowed_in_morning_routine: true,
    allowed_in_evening_routine: false,
    skin_type_suitability: {
      sensitive_skin: true,
      dry_skin: true,
      oily_skin: true,
      combination_skin: true,
    },
    pregnancy_safe: true,
    chief_ingredients: [],
    full_ingredients: [
      'CYCLOPENTASILOXANE',
      'DIMETHICONE CROSSPOLYMER',
      'DIMETHICONOL',
      'ETHYLHEXYL METHOXYCINNAMATE',
      'BUTYL METHOXYDIBENZOYLMETHANE',
      'BENZOPHENONE-3 (OXYBENZONE)',
      'PHOSPHOLIPIDS',
      '1',
      '3-BUTYLENE GLYCOL',
      'CAPRYLIC/CAPRIC TRIGLYCERIDE',
      'CRAMBE ABYSSINICA SEED OIL',
      'BETA-CAROTENE',
      'XANTHOPHYLLS',
      'TOCOPHEROL',
      'HELIANTHUS ANNUUS (SUNFLOWER) SEED OIL',
      'ROSMARINUS OFFICINALIS (ROSEMARY) LEAF EXTRACT',
      'TALC',
      'TITANIUM DIOXIDE',
      'DIMETHICONE',
      'PHENOXYETHANOL',
      'ETHYLHEXYLGLYCERIN',
      'RUBUS IDAEUS (RASPBERRY) SEED OIL',
      'GLYCERIN',
      'CAPSICUM ANNUUM FRUIT EXTRACT',
      'XANTHAN GUM.',
    ],
    clinical_benefits: [],
  },
  {
    product_name: 'derma decode Silicone Gel Sunscreen SPF 50 PA++++ (30ml)',
    allowed_in_morning_routine: true,
    allowed_in_evening_routine: false,
    skin_type_suitability: {
      sensitive_skin: true,
      dry_skin: true,
      oily_skin: true,
      combination_skin: true,
    },
    pregnancy_safe: true,
    chief_ingredients: [],
    full_ingredients: [
      'CYCLOPENTASILOXANE',
      'DIMETHICONE CROSSPOLYMER',
      'DIMETHICONOL',
      'ETHYLHEXYL METHOXYCINNAMATE',
      'BUTYL METHOXYDIBENZOYLMETHANE',
      'BENZOPHENONE-3 (OXYBENZONE)',
      'PHOSPHOLIPIDS',
      '1',
      '3-BUTYLENE GLYCOL',
      'CAPRYLIC/CAPRIC TRIGLYCERIDE',
      'CRAMBE ABYSSINICA SEED OIL',
      'BETA-CAROTENE',
      'XANTHOPHYLLS',
      'TOCOPHEROL',
      'HELIANTHUS ANNUUS (SUNFLOWER) SEED OIL',
      'ROSMARINUS OFFICINALIS (ROSEMARY) LEAF EXTRACT',
      'TALC',
      'TITANIUM DIOXIDE',
      'DIMETHICONE',
      'PHENOXYETHANOL',
      'ETHYLHEXYLGLYCERIN',
      'RUBUS IDAEUS (RASPBERRY) SEED OIL',
      'GLYCERIN',
      'CAPSICUM ANNUUM FRUIT EXTRACT',
      'XANTHAN GUM.',
    ],
    clinical_benefits: [],
  },
  {
    product_name: "derma decode Beginner's Retinol Serum",
    allowed_in_morning_routine: false,
    allowed_in_evening_routine: true,
    skin_type_suitability: {
      sensitive_skin: true,
      dry_skin: true,
      oily_skin: true,
      combination_skin: true,
    },
    pregnancy_safe: false,
    chief_ingredients: ['0.5% Retinol', '5% Niacinamide', '1% Hyaluronic acid'],
    full_ingredients: [
      'AQUA',
      'NIACINAMIDE',
      'PALMITOYL TRIPEPTIDE-1',
      'PALMITOYL TETRAPEPTIDE-7',
      'POLYSORBATE 20',
      'GLYCERIN',
      'BUTYLENE GLYCOL',
      'CARBOMER',
      'BETAINE',
      '1',
      '3-PROPANEDIOL',
      'PICHIA/RESVERATROL FERMENT EXTRACT',
      'RHODIOLA ROSEA ROOT EXTRACT',
      'RHUS CORIARIA LEAF/STEM EXTRACT',
      'SODIUM HYALURONATE',
      'SACCHARIDE ISOMERATE',
      'CITRIC ACID',
      'SODIUM CITRATE',
      'HEPTYL GLUCOSIDE',
      'PENTYLENE GLYCOL',
      'LECITHIN',
      'ALCOHOL',
      'RETINOL',
      'POTASSIUM PHOSPHATE',
      'SPINACIA OLERACEA (SPINACH) LEAF EXTRACT',
      'SODIUM BENZOATE',
      'POTASSIUM SORBATE',
      'SODIUM GLUCONATE',
      'SODIUM HYDROXIDE.',
    ],
    clinical_benefits: [],
  },
  {
    product_name: 'derma decode Daily Use Face Serum for Dry Skin',
    allowed_in_morning_routine: true,
    allowed_in_evening_routine: true,
    skin_type_suitability: {
      sensitive_skin: true,
      dry_skin: true,
      oily_skin: false,
      combination_skin: true,
    },
    pregnancy_safe: true,
    chief_ingredients: [
      '10% Niacinamide',
      '0.1% Sodium Hyaluronate',
      '1% Saccharide Isomerate',
      '0.2% Ceramides',
    ],
    full_ingredients: [
      'AQUA',
      'NIACINAMIDE',
      'BETAINE',
      '1',
      '3-PROPANEDIOL',
      'SACCHARIDE ISOMERATE',
      'CITRIC ACID',
      'SODIUM CITRATE',
      'NYMPHAEA COERULEA FLOWER (BLUE LOTUS) EXTRACT',
      'XANTHAN GUM',
      'LECITHIN',
      'SCLEROTIUM GUM',
      'PULLULAN',
      'PHENETHYL ALCOHOL',
      'SODIUM CARRAGEENAN',
      'SEA SALT',
      'PHENOXYETHANOL',
      'ETHYLHEXYLGLYCERIN',
      'ETHOXYDIGLYCOL',
      'DISODIUM EDTA',
      'CERAMIDE NP',
      'CERAMIDE AP',
      'GLYCOSPHINGOLIPIDS',
      'HYDROGENATED LECITHIN',
      'TETRACETYLHYDROXYPHOSPHINGOSINE',
      'CHOLESTEROL',
      'STEARIC ACID',
      'CAPRYLIC/CAPRIC TRIGLYCERIDE',
      'GLYCERIN',
      'GLYCERYL STEARATE',
      'CETEARYL ALCOHOL',
      '1',
      '2-HEXANEDIOL',
      'SODIUM HYALURONATE.',
    ],
    clinical_benefits: [],
  },
  {
    product_name: 'derma decode Brightening Serum Concentrate for Acne Marks and Pigmentation',
    allowed_in_morning_routine: true,
    allowed_in_evening_routine: true,
    skin_type_suitability: {
      sensitive_skin: true,
      dry_skin: true,
      oily_skin: true,
      combination_skin: true,
    },
    pregnancy_safe: true,
    chief_ingredients: [
      '10% Encapsulated Azelaic Acid',
      '1% Kojic Acid Dipalmitate',
      '0.5% Glycyrrhiza Glabra Root Extract',
    ],
    full_ingredients: [
      'AQUA',
      'POLYGLYCERIN-6',
      'AZELAIC ACID',
      'BETAINE',
      'CAPRYLIC/CAPRIC TRIGLYCERIDE',
      'ALOE BARBADENSIS (ALOE VERA) LEAF EXTRACT',
      'CUCUMIS SATIVUS (CUCUMBER) EXTRACT',
      'KOJIC ACID DIPALMITATE',
      'PEG-40 HYDROGENATED CASTOR OIL',
      'SORBITAN STEARATE',
      'CETEARYL ALCOHOL',
      'CETEARYL GLUCOSIDE',
      'GLYCYRRHIZA GLABRA (LICORICE) EXTRACT',
      'BISABOLOL',
      'ETHYLHEXYLGLYCERIN',
      'PHENOXYETHANOL',
      'CARBOMER',
      'SODIUM GLUCONATE',
      'SODIUM HYDROXIDE.',
    ],
    clinical_benefits: [],
  },
  {
    product_name: 'derma decode Advanced Retinol Serum with Nanoactive Retinaldehyde',
    allowed_in_morning_routine: false,
    allowed_in_evening_routine: true,
    skin_type_suitability: {
      sensitive_skin: false,
      dry_skin: true,
      oily_skin: true,
      combination_skin: true,
    },
    pregnancy_safe: false,
    chief_ingredients: [
      '1% Liposomal Retinol',
      '0.8% Hyaluronic acid',
      '0.5% Nanosomal Retinaldehyde',
    ],
    full_ingredients: [
      'AQUA',
      'CUCUMIS SATIVUS (CUCUMBER) FRUIT EXTRACT',
      'BETAINE',
      'PEG-40 HYDROGENATED CASTOR OIL',
      'GLYCERYL GLUCOSIDE',
      'ALCOHOL',
      'ASCORBYL PALMITATE',
      'BUTYLATED HYDROXYANISOLE',
      'BUTYLATED HYDROXYTOLUENE',
      'LECITHIN',
      'PENTYLENE GLYCOL',
      'POLYSORBATE 20',
      'POTASSIUM PHOSPHATE',
      'RETINOL',
      'TOCOPHEROL',
      'ALLANTOIN',
      'SODIUM CITRATE',
      'SACCHARIDE ISOMERATE',
      'CITRIC ACID',
      'SODIUM HYALURONATE',
      'RETINALDEHYDE',
      'ASCORBIC ACID',
      'PHOSPHOLIPIDS',
      'CAPRYLIC/CAPRIC TRIGLYCERIDE',
      'GLYCERIN',
      'SODIUM BENZOATE',
      'POTASSIUM SORBATE',
      'MYRISTOYL HEXAPEPTIDE-5',
      'DISODIUM EDTA',
      'SODIUM HYDROXIDE.',
    ],
    clinical_benefits: [],
  },
  {
    product_name: 'derma decode Gentle Hydrating Cleanser Face Wash for Dry and Sensitive Skin',
    allowed_in_morning_routine: true,
    allowed_in_evening_routine: true,
    skin_type_suitability: {
      sensitive_skin: true,
      dry_skin: true,
      oily_skin: false,
      combination_skin: true,
    },
    pregnancy_safe: true,
    chief_ingredients: ['2% Betaine', '1% Aloe Vera', '0.5% Hyaluronic Acid', '0.1% Ceramides'],
    full_ingredients: [
      'AQUA',
      'SODIUM METHYL COCOYL TAURATE',
      'ACRYLATES COPOLYMER',
      'COCAMIDOPROPYL BETAINE',
      'SODIUM LAUROYL SARCOSINATE',
      'GLYCERIN',
      'BETAINE',
      'DECYL GLUCOSIDE',
      'DISODIUM COCOYL GLUTAMATE',
      'ARABIDOPSIS THALIANA EXTRACT',
      'ALOE VERA (ALOE BARBADENSIS) LEAF EXTRACT',
      'CAMELLIA SINENSIS (KMT) FRUIT EXTRACT',
      'ETHYLHEXYLGLYCERIN',
      'TASMANNIA LANCEOLATA (MOUNTAIN PEPPER) FRUIT EXTRACT',
      'SODIUM BENZOATE',
      'POTASSIUM SORBATE',
      'PANTHENOL',
      'FRUCTOOLIGOSACCHARIDES',
      'DISODIUM EDTA',
      'CERAMIDE NP',
      'CERAMIDE AP',
      'CERAMIDE EOP',
      'PHYTOSPHINGOSINE',
      'CHOLESTEROL',
      'SODIUM LAUROYL LACTYLATE',
      'CARBOMER',
      'XANTHAN GUM',
      'SODIUM HYDROXIDE.',
    ],
    clinical_benefits: [],
  },
  {
    product_name: 'derma decode After Shave Serum',
    allowed_in_morning_routine: true,
    allowed_in_evening_routine: true,
    skin_type_suitability: {
      sensitive_skin: true,
      dry_skin: true,
      oily_skin: true,
      combination_skin: true,
    },
    pregnancy_safe: true,
    chief_ingredients: [
      'Sodium Hyaluronate 1.5%',
      'Niacinamide 2%',
      'Turmeric Extract 0.5%',
      'Salicylic Acid 1%',
      'Ceramides 0.5%',
    ],
    full_ingredients: [
      'AQUA',
      'BETAINE',
      'ALOE BARBADENSIS (ALOE VERA) LEAF EXTRACT',
      '1',
      '2-PROPANEDIOL',
      'NIACINAMIDE',
      'GLYCERIN',
      'SACCHARIDE ISOMERATE',
      'CITRIC ACID',
      'SODIUM CITRATE',
      'XYLITYLGLUCOSIDE',
      'ANHYDROXYLITOL',
      'XYLITOL',
      'CUCUMIS SATIVUS (CUCUMBER) FRUIT EXTRACT',
      'SALICYLIC ACID',
      'SODIUM HYALURONATE',
      '1',
      '2 HEXANEDIOL',
      'ETHYLHEXYLGLYCERIN',
      'PYRUS MALUS (APPLE) FRUIT EXTRACT',
      'CURCUMA LONGA (TURMERIC) RHIZOME EXTRACT',
      'CERAMIDE NP',
      'CERAMIDE AP',
      'CERAMIDE EOP',
      'PHYTOSPHINGOSINE',
      'CHOLESTEROL',
      'SODIUM LAUROYL LACTYLATE',
      'CARBOMER',
      'XANTHAN GUM',
      'CAMELLIA SINENSIS (GREEN TEA) LEAF EXTRACT',
      'SODIUM BENZOATE',
      'POTASSIUM SORBATE',
      'LACTIC ACID',
      'SODIUM GLUCONATE',
      'SODIUM HYDROXIDE.',
    ],
    clinical_benefits: [],
  },
  {
    product_name: 'derma decode Oil Control Moisturizer for Oily Acne Prone Skin',
    allowed_in_morning_routine: true,
    allowed_in_evening_routine: true,
    skin_type_suitability: {
      sensitive_skin: true,
      dry_skin: false,
      oily_skin: true,
      combination_skin: true,
    },
    pregnancy_safe: true,
    chief_ingredients: [
      '3% Betaine',
      '2% Cucumis Sativus (Cucumber) Fruit Extract',
      '0.5% Allantoin',
      '0.2% Tasmannia Lanceolata Fruit Extract',
    ],
    full_ingredients: [
      'AQUA',
      '1',
      '2 PROPANEDIOL',
      'GLYCERIN',
      'BETAINE',
      'CUCUMIS SATIVUS (CUCUMBER) FRUIT EXTRACT',
      'SODIUM CARBOMER',
      'ALLANTOIN',
      'DIPROPYLENE GLYCOL',
      'POLYSORBATE 20',
      'GARCINIA MANGOSTANA PEEL EXTRACT',
      'MAGNOLIA OFFICINALIS BARK EXTRACT',
      'PUNICA GRANATUM PERICARP EXTRACT',
      'HAMAMELIS VIRGINIANA (WITCH HAZEL) WATER',
      'BENZOIC ACID',
      'ETHYLHEXYLGLYCERIN',
      'PHENOXYETHANOL',
      'ALCOHOL DENAT',
      'TASMANIA LANCEOLATA (MOUNTAIN PEPPER) FRUIT EXTRACT',
      'DISODIUM EDTA',
      'SODIUM HYDROXIDE',
      'CAREOMER.',
    ],
    clinical_benefits: [],
  },
  {
    product_name: 'derma decode Hydrating Face Moisturizer for Dry and Sensitive Skin',
    allowed_in_morning_routine: true,
    allowed_in_evening_routine: true,
    skin_type_suitability: {
      sensitive_skin: true,
      dry_skin: true,
      oily_skin: false,
      combination_skin: true,
    },
    pregnancy_safe: true,
    chief_ingredients: ['2% Sodium Hyaluronate', '3% Betaine', '4% Aloe Leaf Extract'],
    full_ingredients: [
      'AQUA',
      'CAPRYLIC/CAPRIC TRIGLYCERIDE',
      'ISOPROPYL MYRISTATE',
      'ALOE BARBADENSIS (ALOE VERA) LEAF EXTRACT',
      'BETAINE',
      'SORBITAN STEARATE',
      'SUCROSE COCOATE',
      'SODIUM HYALURONATE',
      'CETEARYL ALCOHOL',
      'CETEARYL GLUCOSIDE',
      'XYLITYLGLUCOSIDE',
      'ANHYDROXYLITOL',
      'XYLITOL',
      'BUTYROSPERMUM PARKII (SHEA) SEED BUTTER',
      'POLYSORBATE-20',
      'CETO STEARYL ALCOHOL',
      'PHENETHYL ALCOHOL',
      'SODIUM CARRAGEENAN',
      'SEA SALT',
      'DL-PANTHENOL',
      'PHENOXYETHANOL',
      'ETHYLHEXYLGLYCERIN',
      'TOCOPHERYL ACETATE (VIT E)',
      'DISODIUM EDTA',
      'SODIUM HYDROXIDE.',
    ],
    clinical_benefits: [],
  },
  {
    product_name: 'derma decode After Bite and Rash Cream Stick',
    allowed_in_morning_routine: true,
    allowed_in_evening_routine: true,
    skin_type_suitability: {
      sensitive_skin: true,
      dry_skin: true,
      oily_skin: true,
      combination_skin: true,
    },
    pregnancy_safe: true,
    chief_ingredients: ['Zinc Oxide', 'Bisabolol', 'Hyaluronic Acid', 'Shea Butter'],
    full_ingredients: [
      'ZINC OXIDE',
      'C15-19 ALKANE',
      'CAPRYLIC/CAPRIC TRIGLYCERIDE',
      'AQUA',
      'ETHYLENE/PROPYLENE COPOLYMER',
      'SYNTHETIC WAX',
      'CERA MICROCRISTALLINA',
      'BUTYROSPERMUM PARKII (SHEA) BUTTER',
      'SILICA',
      'PEG 100 STEARATE',
      'GLYCERYL STEARATE',
      'POLYGLYCERYL-2 OLEATE',
      'POLYHYDROXYSTEARIC ACID',
      'POLYGLYCERYL-2 STEARATE',
      'ARACHIDYL ALCOHOL',
      'BEHENYL ALCOHOL',
      'ARACHIDYL GLUCOSIDE',
      'TOCOPHERYL ACETATE (VIT E)',
      'BISABOLOL',
      'HYALURONIC ACID.',
    ],
    clinical_benefits: [],
  },
  {
    product_name: 'derma decode Hair Growth Serum',
    allowed_in_morning_routine: true,
    allowed_in_evening_routine: true,
    skin_type_suitability: {
      sensitive_skin: true,
      dry_skin: true,
      oily_skin: true,
      combination_skin: true,
    },
    pregnancy_safe: true,
    chief_ingredients: [
      '3% Redensyl',
      '1%Procapil',
      '1%Anagain',
      '1%Trifolium Pratense (Clover) Extract',
    ],
    full_ingredients: [
      'SODIUM METABISULFITE',
      'LARIX EUROPAEA WOOD EXTRACT',
      'GLYCINE',
      'ZINC CHLORIDE',
      'CAMELLIA SINENSIS LEAF EXTRACT',
      'ACETYL TETRAPEPTIDE-3',
      'PPG-26-BUTETH-26',
      'APIGENIN',
      'OLEANOLIC ACID',
      'BIOTINOYL TRIPEPTIDE-1',
      'TRIFOLIUM PRATENSE (CLOVER) EXTRACT',
      'PISUM SATIVUM (PEA) SPROUT EXTRACT',
      'INGREDIENTS: AQUA',
      'GLYCERIN',
      '1',
      '2-PROPANEDIOL',
      'BUTYLENE GLYCOL',
      'ALLIUM CEPA (ONION) BULB EXTRACT',
      'PHENOXYETHANOL',
      'SODIUM BENZOATE',
      'HIBISCUS SABDARIFFA FLOWER EXTRACT',
      'ROSMARINUS OFFICINALIS (ROSEMARY) LEAF EXTRACT',
      'BIS-PEG-12 DIMETHICONE',
      'XYLITYLGLUCOSIDE',
      'ANHYDROXYLITOL',
      'MALTITOL',
      'XYLITOL',
      'PLEVEITIA CANALICULATA EXTRACT',
      'SACCHARIDE ISOMERATE',
      'CITRIC ACID',
      'SODIUM CITRATE',
      'ETHYLHEXYLGLYCERINE',
      'HYDROXYETHYLCELLULOSE',
      'DISODIUM EDTA',
      'SODIUM HYDROXIDE.',
    ],
    clinical_benefits: [],
  },
]
