export const available_skincare_products = [
  {
    name: 'derma decode Daily Use Face Serum for Dry Skin',
    usage: {
      am: true,
      pm: true,
    },
    skin_type: {
      sensitive: true,
      dry: true,
      oily: false,
      combination: true,
    },
    safe_in_pregnancy: true,
    chief_ingredients: [
      '10% Niacinamide',
      '0.1% Sodium Hyaluronate',
      '1% Saccharide Isomerate',
      '0.2% Ceramides',
    ],
    ingredients: [
      'AQUA',
      'NIACINAMIDE',
      'BETAINE',
      '1',
      '3-PROPANEDIOL',
      'SACCHARIDE ISOMERATE',
      'CERAMIDES',
      'SODIUM HYALURONATE',
    ],
    benefits: null,
  },
  {
    name: 'derma decode Brightening Serum Concentrate for Acne Marks and Pigmentation',
    usage: {
      am: true,
      pm: true,
    },
    skin_type: {
      sensitive: true,
      dry: true,
      oily: true,
      combination: true,
    },
    safe_in_pregnancy: true,
    chief_ingredients: [
      '10% Encapsulated Azelaic Acid',
      '1% Kojic Acid Dipalmitate',
      '0.5% Licorice Extract',
    ],
    ingredients: [
      'AQUA',
      'AZELAIC ACID',
      'KOJIC ACID DIPALMITATE',
      'LICORICE EXTRACT',
      'BISABOLOL',
    ],
    benefits: null,
  },
  {
    name: 'derma decode Advanced Retinol Serum with Nanoactive Retinaldehyde',
    usage: {
      am: false,
      pm: true,
    },
    skin_type: {
      sensitive: false,
      dry: true,
      oily: true,
      combination: true,
    },
    safe_in_pregnancy: false,
    chief_ingredients: ['1% Liposomal Retinol', '0.5% Nanosomal Retinaldehyde'],
    ingredients: ['RETINOL', 'RETINALDEHYDE', 'SODIUM HYALURONATE', 'PEPTIDES'],
    benefits: null,
  },
  {
    name: 'derma decode Gentle Hydrating Cleanser Face Wash',
    usage: {
      am: true,
      pm: true,
    },
    skin_type: {
      sensitive: true,
      dry: true,
      oily: false,
      combination: true,
    },
    safe_in_pregnancy: true,
    chief_ingredients: ['Betaine', 'Aloe Vera', 'Hyaluronic Acid', 'Ceramides'],
    ingredients: ['SODIUM METHYL COCOYL TAURATE', 'ALOE VERA', 'BETAINE', 'CERAMIDES'],
    benefits: null,
  },
  {
    name: 'derma decode After Shave Serum',
    usage: {
      am: true,
      pm: true,
    },
    skin_type: {
      sensitive: true,
      dry: true,
      oily: true,
      combination: true,
    },
    safe_in_pregnancy: true,
    chief_ingredients: ['Niacinamide', 'Salicylic Acid', 'Turmeric Extract', 'Ceramides'],
    ingredients: ['NIACINAMIDE', 'SALICYLIC ACID', 'TURMERIC EXTRACT', 'CERAMIDES'],
    benefits: null,
  },
  {
    name: 'derma decode Oil Control Moisturizer for Oily Acne Prone Skin',
    usage: {
      am: false,
      pm: false,
    },
    skin_type: {
      sensitive: true,
      dry: false,
      oily: true,
      combination: true,
    },
    safe_in_pregnancy: true,
    chief_ingredients: ['Betaine', 'Cucumber Extract', 'Allantoin'],
    ingredients: ['BETAINE', 'CUCUMBER EXTRACT', 'ALLANTOIN'],
    benefits: null,
  },
  {
    name: 'derma decode Hydrating Face Moisturizer for Dry and Sensitive Skin',
    usage: {
      am: true,
      pm: true,
    },
    skin_type: {
      sensitive: true,
      dry: true,
      oily: false,
      combination: true,
    },
    safe_in_pregnancy: true,
    chief_ingredients: ['Sodium Hyaluronate', 'Betaine', 'Aloe Vera'],
    ingredients: ['SODIUM HYALURONATE', 'ALOE VERA', 'SHEA BUTTER'],
    benefits: null,
  },
  {
    name: 'derma decode After Bite and Rash Cream Stick',
    usage: {
      am: true,
      pm: true,
    },
    skin_type: {
      sensitive: true,
      dry: true,
      oily: true,
      combination: true,
    },
    safe_in_pregnancy: true,
    chief_ingredients: ['Zinc Oxide', 'Bisabolol', 'Shea Butter'],
    ingredients: ['ZINC OXIDE', 'BISABOLOL', 'SHEA BUTTER'],
    benefits: null,
  },
  {
    name: 'derma decode Hair Growth Serum',
    usage: {
      am: true,
      pm: true,
    },
    skin_type: {
      sensitive: true,
      dry: true,
      oily: true,
      combination: true,
    },
    safe_in_pregnancy: true,
    chief_ingredients: ['Redensyl', 'Procapil', 'Anagain'],
    ingredients: ['REDENSYL', 'PROCAPIL', 'ANAGAIN', 'BIOTINOYL TRIPEPTIDE'],
    benefits: null,
  },
  {
    name: 'Sesderma C-Vit Serum',
    usage: {
      am: true,
      pm: true,
    },
    skin_type: {
      sensitive: true,
      dry: true,
      oily: true,
      combination: true,
    },
    safe_in_pregnancy: true,
    chief_ingredients: ['3-O-Ethyl Ascorbic Acid', 'Antioxidant Complex'],
    ingredients: ['ETHYL ASCORBIC ACID', 'RESVERATROL', 'HYALURONIC ACID'],
    benefits: null,
  },
  {
    name: 'Ridacne SA Serum',
    usage: {
      am: false,
      pm: true,
    },
    skin_type: {
      sensitive: false,
      dry: false,
      oily: true,
      combination: true,
    },
    safe_in_pregnancy: false,
    chief_ingredients: ['2% Salicylic Acid', 'Green Tea Extract'],
    ingredients: ['SALICYLIC ACID', 'GREEN TEA EXTRACT'],
    benefits: null,
  },
  {
    name: 'Bioderma Kerato Plus',
    usage: {
      am: false,
      pm: true,
    },
    skin_type: {
      sensitive: false,
      dry: false,
      oily: true,
      combination: true,
    },
    safe_in_pregnancy: false,
    chief_ingredients: ['Salicylic Acid', 'Malic Acid Ester'],
    ingredients: ['SALICYLIC ACID', 'MALIC ACID'],
    benefits: null,
  },
  {
    name: 'Bioderma Night Peel',
    usage: {
      am: false,
      pm: true,
    },
    skin_type: {
      sensitive: false,
      dry: false,
      oily: true,
      combination: true,
    },
    safe_in_pregnancy: false,
    chief_ingredients: ['15% Glycolic Acid'],
    ingredients: ['GLYCOLIC ACID', 'PANTHENOL'],
    benefits: null,
  },
  {
    name: 'Bioderma Atoderm',
    usage: {
      am: true,
      pm: true,
    },
    skin_type: {
      sensitive: true,
      dry: false,
      oily: false,
      combination: true,
    },
    safe_in_pregnancy: true,
    chief_ingredients: ['Niacinamide', 'Glycerin', 'Mineral Oil'],
    ingredients: ['NIACINAMIDE', 'GLYCERIN', 'MINERAL OIL'],
    benefits: null,
  },
  {
    name: 'Juveage Under Eye Cream',
    usage: {
      am: true,
      pm: true,
    },
    skin_type: {
      sensitive: true,
      dry: true,
      oily: true,
      combination: true,
    },
    safe_in_pregnancy: true,
    chief_ingredients: ['Peptides', 'Caffeine', 'Hyaluronic Acid'],
    ingredients: ['PEPTIDES', 'CAFFEINE', 'HYALURONIC ACID'],
    benefits: null,
  },
  {
    name: 'Agevia Exosomes',
    usage: {
      am: false,
      pm: true,
    },
    skin_type: {
      sensitive: false,
      dry: true,
      oily: false,
      combination: true,
    },
    safe_in_pregnancy: false,
    chief_ingredients: ['Exosomes', 'Hebelys®'],
    ingredients: ['EXOSOMES', 'SQUALANE', 'SHEA BUTTER'],
    benefits: null,
  },
  {
    name: 'Melarid TrX',
    usage: {
      am: true,
      pm: true,
    },
    skin_type: {
      sensitive: false,
      dry: true,
      oily: true,
      combination: true,
    },
    safe_in_pregnancy: false,
    chief_ingredients: ['Tranexamic Acid', 'Kojic Acid', 'Alpha Arbutin'],
    ingredients: ['TRANEXAMIC ACID', 'KOJIC ACID', 'ALPHA ARBUTIN'],
    benefits: null,
  },
  {
    name: 'FCL AHA Lightening Gel HQ',
    usage: {
      am: false,
      pm: true,
    },
    skin_type: {
      sensitive: false,
      dry: true,
      oily: true,
      combination: true,
    },
    safe_in_pregnancy: false,
    chief_ingredients: ['Hydroquinone', 'Glycolic Acid'],
    ingredients: ['HYDROQUINONE', 'GLYCOLIC ACID'],
    benefits: null,
  },
  {
    name: 'YUDERMA Eclipse Solaire Active Sunscreen SPF 50 PA+++',
    usage: {
      am: true,
      pm: false,
    },
    skin_type: {
      sensitive: true,
      dry: true,
      oily: true,
      combination: true,
    },
    safe_in_pregnancy: true,
    chief_ingredients: ['Zinc Oxide', 'Titanium Dioxide', 'Niacinamide'],
    ingredients: ['ZINC OXIDE', 'TITANIUM DIOXIDE', 'NIACINAMIDE'],
    benefits: null,
  },
  {
    name: 'Cosmetox Spray',
    usage: {
      am: true,
      pm: true,
    },
    skin_type: {
      sensitive: true,
      dry: true,
      oily: true,
      combination: true,
    },
    safe_in_pregnancy: false,
    chief_ingredients: ['L-Glutathione', 'Vitamin C'],
    ingredients: ['GLUTATHIONE', 'ASCORBIC ACID'],
    benefits: null,
  },
  {
    name: 'Hydra Life Nutraceutical',
    usage: {
      am: true,
      pm: false,
    },
    skin_type: {
      sensitive: true,
      dry: true,
      oily: true,
      combination: true,
    },
    safe_in_pregnancy: false,
    chief_ingredients: ['Collagen Peptide', 'Sodium Hyaluronate', 'ALA'],
    ingredients: ['COLLAGEN', 'HYALURONATE', 'ALPHA LIPOIC ACID'],
    benefits: null,
  },
]
