import { jsPDF } from 'jspdf'
import autoTable from 'jspdf-autotable'

export function useTreatmentPdf() {
  const exportTreatmentPlanPdf = (treatmentPlanData) => {
    const doc = new jsPDF('p', 'pt', 'a4')
    const margin = 40

    // Color palette
    const primaryColor = [41, 128, 185] // blue
    const accentColor = [46, 204, 113] // green
    const softGray = [245, 245, 245]
    const lightBlue = [230, 247, 255]

    // ---------------- COVER PAGE ----------------
    doc.setFillColor(...primaryColor)
    doc.rect(0, 0, 595, 842, 'F')

    doc.setTextColor(255, 255, 255)
    doc.setFont('helvetica', 'bold')
    doc.setFontSize(30)
    doc.text('Professional Treatment Plan', margin, 180)

    doc.setFontSize(16)
    doc.setFont('helvetica', 'normal')
    doc.text(`Total Duration: ${treatmentPlanData.total_time}`, margin, 220)

    doc.setFontSize(12)
    doc.text('Prepared by: Your Clinic Name', margin, 260)
    doc.text('Generated on: ' + new Date().toLocaleDateString(), margin, 280)

    // (Optional) Clinic Logo
    // const logo = new Image()
    // logo.src = '/logo.png'
    // doc.addImage(logo, 'PNG', 420, 120, 120, 60)

    doc.addPage()

    // ---------------- FOOTER ----------------
    const addFooter = () => {
      const pageCount = doc.internal.getNumberOfPages()
      for (let i = 2; i <= pageCount; i++) {
        doc.setPage(i)
        doc.setFontSize(9)
        doc.setTextColor(130)
        doc.text('Generated by Clinic System', margin, 820)
        doc.text(`Page ${i - 1} of ${pageCount - 1}`, 550, 820, { align: 'right' })
      }
    }

    // ---------------- SESSION LAYOUT ----------------
    treatmentPlanData.treatments.forEach((treatment, index) => {
      // Force new page for every session (except first content page)
      if (index !== 0) doc.addPage()
      let y = margin

      // Session banner header background
      doc.setFillColor(...lightBlue)
      doc.rect(0, y - 20, 595, 40, 'F')

      // Session heading text
      doc.setFont('helvetica', 'bold')
      doc.setFontSize(15)
      doc.setTextColor(...primaryColor)

      const wrappedTitle = doc.splitTextToSize(
        `Session ${treatment.session_number}: ${treatment.title}`,
        500,
      )
      doc.text(wrappedTitle, margin, y)
      y += wrappedTitle.length * 16 + 10

      doc.setFont('helvetica', 'normal')
      doc.setFontSize(11)
      doc.setTextColor(80)
      doc.text(`Week: ${treatment.week} | Duration: ${treatment.treatment_time}`, margin, y)
      y += 20

      // ----- Preparations -----
      doc.setFont('helvetica', 'bold')
      doc.setTextColor(40)
      doc.text('Preparations Checklist:', margin, y)
      y += 14
      doc.setFont('helvetica', 'normal')

      treatment.preparations_checklist_for_therapist.forEach((item) => {
        const wrappedText = doc.splitTextToSize(`• ${item}`, 500)
        wrappedText.forEach((line) => {
          doc.text(line, margin + 10, y)
          y += 12
        })
        y += 2
        if (y > 760) {
          doc.addPage()
          y = margin
        }
      })
      y += 10

      // ----- Concerns Addressed -----
      autoTable(doc, {
        startY: y,
        head: [['Concern', 'Current Value', 'Target Value']],
        body: treatment.concerns_addressed.map((c) => [c.concern, c.current_value, c.target_value]),
        theme: 'grid',
        styles: {
          fontSize: 9,
          cellPadding: 4,
          valign: 'top',
          overflow: 'linebreak',
        },
        headStyles: {
          fillColor: primaryColor,
          textColor: 255,
          halign: 'center',
        },
        alternateRowStyles: { fillColor: softGray },
        margin: { left: margin },
      })
      y = doc.lastAutoTable.finalY + 20

      // ----- Steps Table -----
      autoTable(doc, {
        startY: y,
        head: [['#', 'Duration', 'Equipments / Ingredients', 'Procedure']],
        body: treatment.steps.map((s) => [
          s.step_number,
          s.duration + ' min',
          s.ingredients_equipments.join(', '),
          s.how_to_do,
        ]),
        theme: 'grid',
        styles: {
          fontSize: 9,
          cellPadding: 4,
          overflow: 'linebreak',
          valign: 'top',
        },
        headStyles: {
          fillColor: accentColor,
          textColor: 255,
          halign: 'center',
        },
        columnStyles: {
          0: { cellWidth: 25, halign: 'center' },
          1: { cellWidth: 60, halign: 'center' },
          2: { cellWidth: 160 },
          // 3: { cellWidth: 210 },
        },
        alternateRowStyles: { fillColor: softGray },
        margin: { left: margin },
      })
    })

    addFooter()
    doc.save('TreatmentPlan.pdf')
  }

  return { exportTreatmentPlanPdf }
}
